name: Check CHANGELOG.md

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'
      - '.github/workflows/heylogs.yml'
  pull_request:
    paths:
      - 'CHANGELOG.md'
      - '.github/workflows/heylogs.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  heylogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check CHANGELOG.md with heylogs
        uses: jbangdev/jbang-action@03f9f9f6881262b315ec6b6c7d02d8af52ac889a # v0.142.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.19.1:bin
          scriptargs: "check --format github-actions"
